### ISSUE TITLE
Move notebooks to separate directory

### ISSUE THREAD

**Issue by jennyfolkesson** [mehta-lab/multiSero#36]
Version control of notebooks is not fun - minor changes to the notebook will result in massive changes to its json. But they are nice as tutorials. 
I would prefer them to move to their own directory away from the main codebase at least.

**Comment by smguo** [comment]
I noticed the size of the repo is growing fast. As @jennyfolkesson noted in #39, the current repo size is ~120MB. This is much bigger than what it should be given the size of the actual code base. Looks like this is caused by versioning notebooks. I agree it's better not to version actively changing notebooks in the repo.

**Comment by smguo** [comment]
@mattersoflight and I had a discussion on this issue. One solution would be turning the analysis notebook into a CLI that will be called separately. Parameters for analysis will be saved in a config file that serves as input of the CLI.

**Comment by bryantChhun** [comment]
For now, i've moved these to subfolders in pr #57.  However, they are still included in version control.  Once the analysis is fully in CLI form and notebooks can be completely removed, we can close this issue.

**Comment by lenafb** [comment]
Closing for now because multiSero no longer uses notebooks
