### ISSUE TITLE
Tune get_spot_intensity

### ISSUE THREAD

**Issue by jennyfolkesson** [mehta-lab/multiSero#48]
I've noticed that the spot ROIs generated by get_spot_intensity can be a bit off here:
https://github.com/czbiohub/serology-COVID19/blob/robustspotdetection/array_analyzer/workflows/registration_workflow.py#L158

Sometimes it just crops a part of the detected spot, and in one case it detects an artifact. These are from 2020-04-04-14-18-32-COVID_April4_flusecondplate.

B9 - wrong spot in top left
![B9_registration](https://user-images.githubusercontent.com/6796901/79494978-c3088380-7fd8-11ea-819f-b18531d2ae34.png)
![B9_composite_spots_img](https://user-images.githubusercontent.com/6796901/79495003-cc91eb80-7fd8-11ea-8f02-05ba1fa74d85.png)

A6 - mismatching ROIs, only partial spot example in bottom left, one diagonal step up.
![A6_composite_spots_img](https://user-images.githubusercontent.com/6796901/79495201-1b3f8580-7fd9-11ea-9a38-071cfe6a0575.png)

Any thoughts @smguo @bryantChhun ?

**Comment by smguo** [comment]
@jennyfolkesson get_spot_intensity put a detection box that is larger than the spot size around each spot and then segment the largest spot within the detection box. The purpose of this is to refine the spot position to account for small registration error and irregular spot shape. I set the the detection box 4X larger than the spot size but this might be too big and could detect a spurious spot as in B9.

If the segmentation returns a mask then the mask will be used to get the spot intensity. If no mask is returned then a default circular mask will be used. So the box size can change for each spot. I set the threshold to intentionally get masks a bit smaller than the spot. Since it's better to lose some pixels on the border than risk including background pixels that will bias the spot intensity. 

This is only a quick fix to match the spot intensity to Scienion output. It can definitely use a bit more tuning or even replaced by a better approach...

**Comment by smguo** [comment]
![A1_composite_spots_prop](https://user-images.githubusercontent.com/18110744/79499231-7eccb180-7fdf-11ea-89c6-4649e0d2f7da.png)
This is the image with the final masks overlaid on each spot

**Comment by bryantChhun** [comment]
> I've noticed that the spot ROIs generated by get_spot_intensity can be a bit off here:

Additionally, I found that spots A8 and A9 are badly off:
A8
![A8_composite_spots_img](https://user-images.githubusercontent.com/25647712/79522572-ec450600-8010-11ea-8a78-8a7753b9fab3.png)
A9
![A9_composite_spots_img](https://user-images.githubusercontent.com/25647712/79522583-f109ba00-8010-11ea-86a8-0dbc275a2df7.png)

The centering shows a slight shift too:
A8
![A8_registration](https://user-images.githubusercontent.com/25647712/79524086-75117100-8014-11ea-9610-a3a204f1baf8.png)

A9
![A9_registration](https://user-images.githubusercontent.com/25647712/79524889-780d6100-8016-11ea-8553-4dccdafc273d.png)


I tried tweaking some of the get_spot_intensity parameters, (increasing, decreasing "large" bounding box) but none improved the results.  Will continue soon.

**Comment by smguo** [comment]
@bryantChhun For A8 & A9 the bboxs are off mainly because the grid is off. `get_spot_intensity` can fix small registration error but not big offset like in this case. In each image one of the 5 fiducials is missing so grid registration is off. You can try tuning OpenCV blob detector to get all the 5 fiducials and that should fix registration. It might mess up registration in other wells though...

**Comment by bryantChhun** [comment]
Fixed in PR #34, #45 
Closing

**Comment by jennyfolkesson** [comment]
This is still an issue in some cases, see B9 (top image in issue) and B12 (below) on 04-04
![B12_composite_spots_img](https://user-images.githubusercontent.com/6796901/80245741-18b7de00-8620-11ea-83c3-b1dc35924233.png)

**Comment by jennyfolkesson** [comment]
Closing this with https://github.com/czbiohub/pysero/pull/69
Could reopen if we find that it needs further tuning when spots are not aligned with grid.
