### ISSUE TITLE
Region props returns unusual images

### ISSUE THREAD

**Issue by bryantChhun** [mehta-lab/multiSero#7]
Looking at the underlying intensity images of every regionprop, it appears to be bound to a circle with some bright boundaries:

[Google Slide with pics](https://docs.google.com/presentation/d/1GnRtmLBS2s5AXhL-cycAhj03S9UWUiD3yL9pUMcYR1w/edit?usp=sharing)

The potential concerns are :
- regionprop centroid moves too far from expected position for "comet" spots
- The underlying intensity image does not reflect the image in the bounding box.  Instead it appears to be bound by a circle (not necessarily the mask) 

I will investigate the effect of the eccentricity filter on these spots

**Comment by mattersoflight** [comment]
Combination of current segmentation and filtering parameters miss many spots, especially ones that are dim. Here is an overlay of images of wells and locations assigned by `generate_props_dict`. Spot detection anomalies that you see may be related to this:

![image](https://user-images.githubusercontent.com/2934183/77728323-8210e680-6fb9-11ea-86b1-6842cef6274d.png)

![image](https://user-images.githubusercontent.com/2934183/77728468-ce5c2680-6fb9-11ea-8725-b54aff694340.png)
![image](https://user-images.githubusercontent.com/2934183/77728526-e633aa80-6fb9-11ea-8497-ac8d06b2e979.png)

**Comment by mattersoflight** [comment]
The mis-assignment of spots is coming from initialization of `props_array` and `bgprops_array` variables outside of the loop.

When I exported the ODs in a 2D array constructed from props_array, I saw this for well A4 when props_array is initialized outside of the loop:

  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1.563201 | 1.345141 | 2.997746 | 2.099849 | 1.298738 | 1.656746 | 1.234147 | 1.612831
1 | 1.445509 | 1.374727 | 2.966517 | 1.26165 | 1.434695 | 1.727706 | 1.693654 | 3.557503
2 | 1.878842 | 1.283533 | 2.784524 | 1.269079 | 3.145995 | 1.286808 | 1.879973 | 1.764097
3 | 1.930243 | 1.263281 | 1.161575 | 1.27429 | 2.603671 | 1.589525 | 1.884354 | 1.671318
4 | 1.747058 | 1.263491 | 3.271377 | 1.74045 | 1.175276 | 2.221479 | 1.468281 | 4.615932
5 | 1.447847 | 1.286702 | 1.528258 | 1.237907 | 2.430797 | 2.050472 | 1.349602 | 1.405774

This is not correct, because as above image shows, many spots are not detected in well A4.

Once props_array is initialized inside the loop, et voila:

  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | -- | --
0 |   | 1.345141 | 2.997746 |   | 1.298738 |   | 1.234147 | 1.612831
1 | 1.445509 |   | 2.966517 | 1.26165 |   |   |   | 3.557503
2 | 1.878842 | 1.283533 |   |   |   |   |   |  
3 | 1.930243 |   | 1.161575 |   |   |   |   |  
4 | 1.747058 |   |   |   | 1.175276 |   |   |  
5 | 1.447847 |   |   | 1.237907 |   |   |   | 1.405774

**Comment by bryantChhun** [comment]
good and important catch, this explains quite a few things -- like how we saw an off-center spot where there should not have been any spot
